config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => 'user_registrations'}
  
  resources :users 
  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :payments
  
  mount ActionCable.server => '/cable'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  get 'orders/index'

  get 'users/new'

  get 'products/new'

  get '/products/:id/edit' => 'products#edit'

  post 'payments/create'

  get 'comments/edit'

  #get 'products/:id' => 'products#show'#

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer>
  <div class="container text-center">
    <p class="navbar-text col-md-12">&copy; 2016 bike BK | Site Built By Christian Velez.</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
     <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsible">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" id="logo"<%=link_to image_tag("bike_logo4.png", class: "img"), root_path %><img /></a>
      </div>
      
      <div class="navbar-collapse collapse" id="navbar-collapsible">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'Home', static_pages_index_path %></li>
          <li><%= link_to 'About', static_pages_about_path %></li>
          <li><%= link_to 'Contact', static_pages_contact_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Store<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to 'Orders', orders_path %></li>
                <li>
                  <% if user_signed_in? %>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                  <% else %>
                    <%= link_to('Login', new_user_session_path) %>
                  <% end %>
                </li>
                <li>
                    <% if current_user && current_user.admin? %>
                    <%= link_to('Add Product', new_product_path) %>
                    <% end %>
                  </li>
                <li class="divider"></li>
            </ul>
          </li>
         </ul>
          
        <%= form_tag("/products", method:"GET", class: "navbar-form") do %>
        <div class="input-group navbar-right">
          <%= label_tag(:q, "Search for:", class: "hidden") %>
          <%= text_field_tag(:q, "", placeholder: "Search", class: "form-control ") %>
            <span class="input-group-btn">
                <%= button_tag name: nil, class: "btn btn-default", type: "submit" do %>
                <span class="glyphicon glyphicon-search"></span>
                <% end %>
            </span>
        </div>
        <% end %>
      </div>
   </div>
  </nav>

  <!--#params[:product_id]-->

app/views/shared/_product.html.erb
<% cache product do %>
<div class=" col-sm-6 col-md-6 col-lg-4  product-listings" id="featured">
  <%= link_to image_tag(product.image_url, class: "img-responsive prod-img img-zoom", data_zoom_image: product.image_url ), product %>
  <p class="lead"><strong><%= product.name %></strong></p>
  <p><%= product.description %></p>
  <p><%= product.color %></p>
  <p>Starting at $<%= product.price %></p>
</div><!-- /col -->
<% end %>

app/views/shared/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="<%= @product.image_url %>"
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %>"
  data-amount="<%= (@product.price*100).to_i %>">>
</script>