config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => 'user_registrations'}
  
  resources :users 
  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :payments
  
  mount ActionCable.server => '/cable'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  get 'orders/index'

  get 'users/new'

  get 'products/new'

  get '/products/:id/edit' => 'products#edit'

  post 'payments/create'

  get 'comments/edit'

  #get 'products/:id' => 'products#show'#

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments

  validates :name, presence: true
  validates :price, presence: true
  validates :color, presence: true

  def average_rating
    comments.average(:rating).to_f
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    #byebug
    if Rails.env.development?
      if params[:q]
        search_term = params[:q]
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      else
        @products = Product.all
      end
    else
      if params[:q]
        search_term = params[:q]
        @products = Product.where("name ilike ?", "%#{search_term}%")
      else
        @products = Product.all
      end
    end
  end


  # GET /products/1
  # GET /products/1.json
  def show
    #@product = Product.find(params[:id])#
    #byebug
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    #byebug
    @product = Product.new(product_params)
    #logger commented out in favor of byebug
    #logger.debug {"New product: #{@product.attributes.inspect}"}
    #logger.debug {"Product should be valid #{@product.valid?}"}
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        #logger.debug "The product was saved and the user will be redirected"
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
             <% if signed_in? && current_user.admin? %>
             <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
             <% end %>
             </p>
            <p><div class="rated first" data-score="<%= comment.rating %>"></div></p>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

<%= will_paginate @comments, renderer: BootstrapPagination::Rails, :page_links => false %>

app/views/products/_edit_comment.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
             <% if signed_in? && current_user.admin? %>
             <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
             <% end %>
             </p>
            <p><div class="rated first" data-score="<%= comment.rating %>"></div></p>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

<%= will_paginate @comments, renderer: BootstrapPagination::Rails, :page_links => false %>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Product',  class: "btn btn-default"   %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body, class: "form-control"%>
    </p>
    <p>
      <div class="rating"></div>
    </p>  
    <p>
      <%= f.submit "Submit", class: "btn btn-default"  %>
    </p>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<div class="container">
<div class="row">
<div class="col-md-4 col-md-offset-4">
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

</div>
</div>
</div>

app/views/products/index.html.erb
<% provide(:title, "Products") %>


<p id="notice"><%= notice %></p>

<h3 class="product-heading">our collection</h3>

<table class = "products">

<div class="container">
  <div class="row text-center">
    <% cache(cache_key_for_products) do %>
    <% @products.each do |product| %>
      
       <%= render partial: 'shared/product', locals: { product: product } %>
     
    <% end %> 
    <% end %> 
  </div>
</div>

<br>

<% link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-4 col-md-offset-4 top">

<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

</div>
</div>
</div>

app/views/products/show.html.erb
<% cache @product do %>
<div class="container">
<div class="row tex-center" data-product-id="<%= @product.id %>">
<div class="col-md-6 top review1">
<p id="notice"><%= notice %></p>

<%= image_tag(@product.image_url, class: "img-responsive show-img prod-img img-zoom", data_zoom_image: @product.image_url) %>


<p>
  <h3><%= @product.name %></h3>
</p>

<p>
  <%= @product.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Price: $</strong>
  <%= @product.price %>
</p>

<p>Average Rating: 
  <div class="rated" id= "average-rating" data-score="<%= @product.average_rating %>"></div>
</p>

<p>
  <div class="stripe">
  <%= form_tag 'payments/create' do %>
     <%= render partial: "shared/stripe_checkout_button" %>
  <% end %>  
  </div>
</p>
<% end %>
</div>
<div class="col-md-4 col-md-offset-1 top review">
<%= render 'new_comment' %>

<div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>

<%= render 'comments' %>
<% if current_user && current_user.admin? %>
<%= link_to 'Edit Comments', edit_product_comment_path(@product. comments) %>
<% end %>
</div>


<% link_to 'Edit', edit_product_path(@product) %> 
<% link_to 'Back', products_path %>

</div>
</div>